opentracing:
  jaeger:
    log-spans: true
    service-name: booster-ot
    enable-b3-propagation: true
---
spring:
  profiles: local
opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
